name: README build

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0,12 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository to Main branch
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Setup NodeJs 20.x
        uses: actions/setup-node@v1
        with:
          node-version: '20.x'
      - name: Cache dependencies and build outputs to improve workflow execution time.
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}
      - name: Install dependencies
        run: npm install
      - name: Generate README file
        run: node index.js
        env: 
          YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
          YOUTUBE_USER_ID: ${{ secrets.YOUTUBE_USER_ID }}
      - name: Commit changes
        run: |
          git config --global user.email "webcarpi@gmail.com"
          git config --global user.name "carpicoder"
          git add .
          git commit -m "Update README"
      - name: Push changes to Main branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
